export enum UserRole {
  SIGNATORY = 'SIGNATORY',
  APPROVER = 'APPROVER',
  VIEWER = 'VIEWER',
  DELEGATOR = 'DELEGATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum EnvelopeStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  REVISION = 'REVISION',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum CircuitType {
  SEQUENTIAL = 'SEQUENTIAL',
  PARALLEL = 'PARALLEL',
  MIXED = 'MIXED',
  CONDITIONAL = 'CONDITIONAL',
}

export enum RecipientRole {
  SIGNATORY = 'SIGNATORY',
  APPROVER = 'APPROVER',
  VIEWER = 'VIEWER',
  DELEGATOR = 'DELEGATOR',
}

export enum RecipientStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  SIGNED = 'SIGNED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DELEGATED = 'DELEGATED',
  RETURNED = 'RETURNED',
}
